apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-circleci
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-circleci
  template:
    metadata:
      labels:
        app: mlops-circleci
    spec:
      containers:
      - name: mlops-circleci
        image: us-central1-docker.pkg.dev/affable-operand-454200-b7/mlops-circleci/mlops-circleci:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: mlops-circleci
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
